config/routes.rb
IconHaiku::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  namespace :api do 
    resources :haikus 
    resources :tags
    resources :nouns
  end

  get "home/index"
  match "create" => 'home#create'
  match "share/:slug" => "home#share"

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def create
  end

  def share
    @slug = params[:slug]
    @haiku = Api::Haiku.find_by_slug(@slug)
    noun_ids = [
      @haiku[:line1_slot1_id],
      @haiku[:line1_slot2_id],
      @haiku[:line1_slot3_id],
      @haiku[:line1_slot4_id],
      @haiku[:line1_slot5_id],
      @haiku[:line2_slot1_id],
      @haiku[:line2_slot2_id],
      @haiku[:line2_slot3_id],
      @haiku[:line2_slot4_id],
      @haiku[:line2_slot5_id],
      @haiku[:line2_slot6_id],
      @haiku[:line2_slot7_id],
      @haiku[:line3_slot1_id],
      @haiku[:line3_slot2_id],
      @haiku[:line3_slot3_id],
      @haiku[:line3_slot4_id],
      @haiku[:line3_slot5_id]
    ]
    @nouns = {};
    begin
      noun_ids.each do |n|
        @nouns[n] = Api::Noun.find(n).icon_url
      end
    rescue
    end


  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/create.html.haml
.row
  .span8
    %h3.script-font Icon Haiku
    %strong Drag and drop some icons:
    %ul#haiku{:"data-update-url" => "/api/haikus.json"}
      %li
        %ul#line1.haikuLine{:"data-limit" => 5}
      %li
        %ul#line2.haikuLine{:"data-limit" => 7}
      %li  
        %ul#line3.haikuLine{:"data-limit" => 5}
      %li
        %ul#deleteLine.haikuLine{:"data-limit" => 0}
  .span3#app{ :'ng-app' => 'NounApp', :'ng-controller' => 'NounCtrl' }
    %h3.script-font
      Choose wisely:
    
    .tags
      %input{type:"hidden", id:"tagSelect", style:"width:250px", value:""}

    %ul#library{:'when-scrolled' => "loadMore('')"}
      %li.tile{:'ng-repeat'=>'noun in nouns', draggable: ""}
        %img{:id => "{{noun.id}}", :rel => "tooltip",:'ng-src' => "{{noun.icon_url}}", :alt => '{{noun.name}}, {{noun.attribution}}'}
        -#Name: {{noun.name}}, Attribution: {{noun.attribution}}
.row.well
  %h4.span5
    Title Your Haiku
    %input#haikuTitle{type: "text", required: "required"}
  .offset1
  .span5
    %a#saveButton.btn
      %h5
        Save Haiku
  .clearfix

app/views/home/index.html.haml
.span12#buffer
  -#.span1
    = image_tag "box.png"
  %h1.span6.offset2.script-font What is Icon Haiku?
.span12
  .row
    .span7.offset2
      Poetry from icons. Skip over language barriers. Really leave interpretation
      up to the reader. Write Haiku for anyone.
  .row
    -#%p Poetry 2.0. Quirky Haiku with the rich and cutting imagery of icons.  
    .span7.offset2
      -#= image_tag "generator.png"
      Use our 
      %em 
        Icon Haiku
      generator and generate your own obscure image poetry, or just view the work of others... whatever works for you.
      %p 
        Click the 
        %strong Start Your Own
        button and let your creative juices flow.
  .row
    .span5.offset7{:style=>"margin-bottom:25px;"}
      = link_to "<i class='icon-leaf icon-white'></i> Start Your Own".html_safe, create_path, {class: "btn btn-success"}
-#.span12
  %h1 HAIKU GOES HERE

app/views/home/share.html.haml
.row{:'ng-controller' => "HaikuCtrl"}
  .span12
    %h2.script-font
      Haiku - 
      = @haiku.name
  .row
    .span11.offset1
      %ul#showhaiku
        %li
          %ul.haikuLine
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line1_slot1_id]}", id:"#{@haiku.line1_slot1_id}"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line1_slot2_id]}", id:"#{@haiku.line1_slot2_id}"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line1_slot3_id]}", id:"#{@haiku.line1_slot3_id}"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line1_slot4_id]}", id:"#{@haiku.line1_slot4_id}"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line1_slot5_id]}", id:"#{@haiku.line1_slot5_id}"}
            
        %li
          %ul.haikuLine
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line2_slot1_id]}", id:"#{@haiku.line2_slot1_id}" ,alt:"Test"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line2_slot2_id]}", id:"#{@haiku.line2_slot2_id}" ,alt:"Test"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line2_slot3_id]}", id:"#{@haiku.line2_slot3_id}" ,alt:"Test"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line2_slot4_id]}", id:"#{@haiku.line2_slot4_id}" ,alt:"Test"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line2_slot5_id]}", id:"#{@haiku.line2_slot5_id}" ,alt:"Test"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line2_slot6_id]}", id:"#{@haiku.line2_slot6_id}" ,alt:"Test"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line2_slot7_id]}", id:"#{@haiku.line2_slot7_id}" ,alt:"Test"}
        %li  
          %ul.haikuLine
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line3_slot1_id]}", id:"#{@haiku.line3_slot1_id}" ,alt:"Test"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line3_slot2_id]}", id:"#{@haiku.line3_slot2_id}" ,alt:"Test"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line3_slot3_id]}", id:"#{@haiku.line3_slot3_id}" ,alt:"Test"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line3_slot4_id]}", id:"#{@haiku.line3_slot4_id}" ,alt:"Test"}
            %li.tile.big
              %img{:src=>"#{@nouns[@haiku.line3_slot5_id]}", id:"#{@haiku.line3_slot5_id}" ,alt:"Test"}
  .row
    .span11.well
      .offset1.span5
        Share this on Twitter!
        %a.twitter-share-button{href:"https://twitter.com/share", :'data-text'=>"Checkout this Icon Haiku", :'data-url' => "http://www.iconhaiku.com/share/#{@haiku.slug}",:'data-size'=>"large", :'data-hashtags' => "iconhaiku"}
          Tweet
          = render('twitter')
      .span4
        = link_to "<i class='icon-leaf icon-white'></i> Start Your Own".html_safe, create_path, {class: "btn btn-success"}
        